---
- name: install essential packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-pip

- name: add the gpg key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: add apt repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

- name: install docker
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - docker-engine

- name: install docker-py
  pip: name=docker-py