---
- name: "download docker release {{docker_release}}"
  get_url:
    url: "{{docker_release}}"
    dest: "/opt/docker-release-{{docker_release | hash('md5')}}"
  when: docker_release is defined and docker_release != ""

- name: "install docker release {{docker_release}}"
  apt:
    deb: "/opt/docker-release-{{docker_release | hash('md5')}}"
  when: docker_release is defined and docker_release != ""