---
# https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#uninstall-old-versions

- name: "remove deprecated engines"
  apt:
    name: "{{item}}"
    state: absent
    purge: yes
  with_items:
    - docker
    - docker.io
    - docker-engine
  when: docker_uninstall_deprecated_engines == "yes"

# https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-from-a-package

- name: "install docker release"
  apt:
    deb: "{{docker_release}}"